version: '3.9'

services:
  next-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NEXT_PUBLIC_GITHUB_CLIENT_ID: bce6d84e17efad8b028c
