name: Next CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "NEXT_PUBLIC_GITHUB_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }}" >> .env
      - name: Build docker image
        run: docker build -t abnerst/next .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Publish image to docker hub
        run: docker push abnerst/next:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull abnerst/next:latest
      - name: Delete old container
        run: docker rm -f next-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name next-app-container abnerst/next